version: "3.8"

services: 
    mongo:
        container_name: mongo
        ports: 
            - 27017:27017
        image: mongo:4.4.5-bionic
        volumes: 
            - db_data:/data/db
volumes: 
    db_data:
        name: db_data